### ISSUE TITLE
Remove setup_tatodetect from setup_external_tools.yml

### ISSUE THREAD

**Issue by Poulpisator** [Tatoeba/imouto#46]
If executed, the playbook will fail because the role 'setup_tatodetect' was not found. 
Indeed, there is no such role and looking at tatoeba.tasks.yml, Tatodetect installation follows 
```
- name: Install and setup Tatodetect
  import_tasks: install.yml
  vars:
    repo: https://github.com/Tatoeba/Tatodetect
    force_install: no
```

So I think `- { role: setup_tatodetect, force_install: no }` should be deleted / replaced / updated.
